services:
  - type: web
    name: TenkaiTechBackend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn online_store.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'your-render-subdomain.onrender.com,localhost,127.0.0.1'
      - key: MONGO_URI
        value: your-mongodb-uri
